### PR TITLE
DOC Move configration info to core documentation

### PR DESCRIPTION
**Pull request by maxime-rainville**
# Parent issue
* https://github.com/silverstripe/silverstripe-framework/issues/8782

### CODE REVIEW

**Review by dnsl48 — APPROVED** [review]

**Comment by robbieaverill** [comment]
We need to remove PHP 5.6 from the builds, or limit the SS versions we're testing against so it doesn't pull in PHP 7 only syntax

**Comment by maxime-rainville** [comment]
The problem is that there's nothing that constrain assets 1.5.0 to a specific PHP version, so it tries to install framework 4.4 with assets 1.5.0. I've just pushed a tweak to install specific version of recipe-core which will prevent mismatched assets/framework combination.

This kind of sucks, but short of going back and re-tagging assets 1.5.0, there's not much we can do.

**Comment by robbieaverill** [comment]
I see. Going back and re-tagging isn't really an option. Maybe let's just remove the 5.6 builds from Travis.

**Comment by maxime-rainville** [comment]
I'm thinking there's some value in keeping testing PHP 5.6. If we get to a point where supporting PHP5.6 gets in our way, then we officially drop support for it by adding a PHP constraint and removing PHP56 from the build.

**Comment by robbieaverill** [comment]
The only value it provides in my eyes is a syntax test to make sure people don't accidentally merge PHP 7 syntax before the module is ready for it... we don't support PHP 5.6 any more (7.1 minimum as of Silverstripe 4.5, right?) so where situations like this come up I'd suggest scrapping it. I see you've greened the tests though, so all good

**Pull request merged**
